### ISSUE TITLE
Other forks of mapbox-gl-js

### ISSUE THREAD

**Issue by ajinkya** [maps-gl/maps-gl#21]
Hello,

As mentioned in the readme, here are some other forks by folks in the ecosystem, it would be great if we can all merge and contribute in a single repo:

[https://github.com/openmaptiles/gl-js](https://github.com/openmaptiles/gl-js)
[https://github.com/stadiamaps/mapbox-gl-js-oss](https://github.com/stadiamaps/mapbox-gl-js-oss)

Thanks.

**Comment by lseelenbinder** [comment]
Hi @ajinkya, all of the good people involved with the various forks are discussing this in a few minutes on a call. We definitely want a unified approach!

**Comment by kylebarron** [comment]
It would be great if you could post a writeup in an issue about the result of the call. Fyi I've also seen activity today on this other fork: https://github.com/MapLibre/maplibre-gl-js

**Comment by lseelenbinder** [comment]
https://github.com/MapLibre/maplibre-gl-js is the official fork going forward, based on agreement by the parties here: https://docs.google.com/document/d/1UB8VJ6_vMD9Zxfem7cunwa_G-hXo_ZRY1IeF5iGlh4w/edit?usp=sharing.

We strongly hope @snickell and team will join us, as we are in agreement as to the goals and structure of the community fork. Of course, they're under no obligation to do so, and if they continue with this project, we wish them the best!

**Comment by kylebarron** [comment]
Thanks for the response and putting the summary into into a Google Docs. It would be great if you could add that to this repo's README to point users to the right place.
