### ISSUE TITLE
Fork Mapbox TypeScript types as well

### ISSUE THREAD

**Issue by GarrettCannon** [maps-gl/maps-gl#22]
Hello,

I definitely appreciate the efforts here. My suggestion would be to fork [https://www.npmjs.com/package/@types/mapbox-gl](https://www.npmjs.com/package/@types/mapbox-gl) as well to be used with this library. 
Ideally it could be fully merged into this repo to further reduce fragmentation. 
I don't know how the maintainers want to go about this, but if I can help let me know.

Thanks!

**Comment by vinayakkulkarni** [comment]
Yep yep yep.. Typings are a must if we want to totally migrate from mapbox-gl-js 1.x to `maps-gl`
