### ISSUE TITLE
Get a chat room going

### ISSUE THREAD

**Issue by snickell** [maps-gl/maps-gl#3]
Or chose another way to have discussions, this is fairly urgent since its possible mapbox won't want us using their issue tracker to coordinate forks ;-)

**Comment by snickell** [comment]
CURRENTLY GOING WITH: gitter.im

**Comment by snickell** [comment]
I'm using this public domain image as an icon for now:
![map-map-marker-icon](https://user-images.githubusercontent.com/223277/101579804-52a2de00-397e-11eb-971e-ab877063feee.png////)

**Comment by lujieha** [comment]
maps-gl ，no room search results in gitter.im

**Comment by snickell** [comment]
Yeah, I gotta add org privs to gitter.im for it.... just a little longer :)

**Comment by snickell** [comment]
OK! https://gitter.im/maps-gl/maps-gl is live
