### ISSUE TITLE
Another fork

### ISSUE THREAD

**Issue by stevage** [maps-gl/maps-gl#4]
https://github.com/stadiamaps/mapbox-gl-js-oss

You should collaborate?

**Comment by snickell** [comment]
Thank you @stevage ! I've opened an issue there (https://github.com/stadiamaps/mapbox-gl-js-oss/issues/1) as a way of reaching out to them, and invited them as an owner of this project. So far it looks like they've mainly done a clone on a tag history, and a small README change, so hopefully they too will see the value of avoiding fragmentation.

**Comment by snickell** [comment]
BTW, happy to chat on gitter: https://gitter.im/maps-gl/maps-gl

**Comment by stevage** [comment]
Another https://github.com/MapLibre/maplibre-gl-js

**Comment by stevage** [comment]
Another https://github.com/openmaptiles/gl-js
